name: Tests

on:
  push:
    branches: [ ci-tests ]
  pull_request:
    branches: [ ci-tests ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
    
      - name: Install dependencies
        run: pdm install    
      - name: Install dev dependencies
        run: pdm install -d    
      - name: Run tests
        run: |
          pdm run pytest -xvs tests/test_settings_manager.py
      - name: Generate coverage report
        run: |
          pdm run pytest --cov-report=term --cov-report=xml -p no:warnings --cov=src/local_deep_research
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v4
#        with:
#          file: ./coverage.xml
#          fail_ci_if_error: false