name: Tests

on:
  push:
    branches: [ ci-tests ]
  pull_request:
    branches: [ ci-tests ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Force add pytest
        run: pdm add -dG dev pytest pytest-mock pytest-cov
      - name: Install dev dependencies
        run: pdm install -d
      - name: Run tests
        run: |
          /home/runner/work/local-deep-research/local-deep-research/.venv/bin/pytest -xvs tests/test_settings_manager.py
      - name: Generate coverage report
        run: |
          pytest --cov=src/local-deep-research --cov-report=xml --cov-branch --cov-fail-under=0 -p no:warnings -vv tests/test_settings_manager.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
